---
#配置你的api key
algolia:
  index: "your algolia index"
  admin-key: "your algolia admin key"
  app-id: "your algolia appID"

#字典和停用词位置
#使用data目录会让hugo命令报错
segment:
  dict:
    path: "dict/dict.txt"
    stop-path: "dict/stop.txt"

#配置http代理(可选)
#http:
#  httpProxy: "127.0.0.1:1087"
---