---
## config hugo-algolia-updater
algolia-updater:
  ## config algolia
  algolia:
    index: "your algolia index"
    admin-key: "your algolia admin key"
    app-id: "your algolia appID"

  ## config dict and stop words dict
  # use `data` dir under Hugo project may cause Hugo panic, so we use `dict` here
  segment:
    dict:
      path: "dict/dict.txt"
      stop-path: "dict/stop.txt"
---